[project]
name = "du"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=1.0.0",
    "chromadb>=1.5.8",
    "python-dotenv>=1.2.2",
    "tqdm>=4.67.3",
    "imap-tools>=1.15.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "ruff>=0.15.12",
]
